=== roydmerkel/xu4/conf/dtd/graphics.dtd
<!-- $Id$ -->

<!ENTITY % bool '( true | false )'>
<!ENTITY % filetype '( raw | rle | lzw )'>
<!ENTITY % fixup '( none | intro | introExtended | abyss | abacus )'>
<!ENTITY % layouttype '( standard | gem )'>
<!ENTITY % transformtype '( invert | pixel )'>

<!ELEMENT graphics ( imageset | layout | tileanimset )+ >

<!ELEMENT imageset ( image+ ) >
<!ATTLIST imageset name           NMTOKEN  #REQUIRED
                   extends        NMTOKEN  #IMPLIED>

<!ELEMENT image ( subimage* ) >
<!ATTLIST image name              NMTOKEN  #REQUIRED
                filename          CDATA    #REQUIRED
                width             NMTOKEN  #REQUIRED
                height            NMTOKEN  #REQUIRED
                depth             NMTOKEN  #REQUIRED
                prescale          NMTOKEN  #IMPLIED
                filetype          %filetype; #REQUIRED
                tiles             NMTOKEN  #IMPLIED
                introOnly         %bool;   #IMPLIED
                transparentIndex  NMTOKEN  #IMPLIED
                xu4Graphic        %bool;   #IMPLIED
                fixup             %fixup;  #IMPLIED>

<!ELEMENT subimage EMPTY >
<!ATTLIST subimage name           NMTOKEN  #REQUIRED
                   x              NMTOKEN  #REQUIRED
                   y              NMTOKEN  #REQUIRED
                   width          NMTOKEN  #REQUIRED
                   height         NMTOKEN  #REQUIRED>

<!ELEMENT layout ( tileshape, viewport ) >
<!ATTLIST layout name             CDATA    #REQUIRED
                 type             %layouttype; #REQUIRED>

<!ELEMENT tileshape EMPTY >
<!ATTLIST tileshape width         NMTOKEN  #REQUIRED
                    height        NMTOKEN  #REQUIRED>

<!ELEMENT viewport EMPTY >
<!ATTLIST viewport x              NMTOKEN  #REQUIRED
                   y              NMTOKEN  #REQUIRED
                   width          NMTOKEN  #REQUIRED
                   height         NMTOKEN  #REQUIRED>

<!ELEMENT tileanimset ( tileanim+ ) >
<!ATTLIST tileanimset name        NMTOKEN  #REQUIRED>

<!ELEMENT tileanim ( transform+ ) >
<!ATTLIST tileanim name           NMTOKEN  #REQUIRED>

<!ELEMENT transform ( color* ) >
<!ATTLIST transform type          %transformtype; #REQUIRED
                    x             NMTOKEN  #IMPLIED
                    y             NMTOKEN  #IMPLIED
                    width         NMTOKEN  #IMPLIED
                    height        NMTOKEN  #IMPLIED>

=== roydmerkel/xu4/u4/conf/graphics.xml
<?xml version="1.0"?>
<!DOCTYPE graphics SYSTEM "dtd/graphics.dtd">
<!-- $Id$ -->
<graphics>
    <imageset name="EGA">
        <!-- tiles, charset, and game border -->
        <image name="tiles"    filename="shapes.ega" width="16" height="4096" depth="4" filetype="image/x-u4raw" tiles="256"/>
        <image name="charset"  filename="charset.ega"  width="8"  height="2048" depth="4" filetype="image/x-u4raw" tiles="256"/>
        <image name="borders"  filename="start.ega"    width="320" height="200" depth="4" filetype="image/x-u4rle"/>

        <!-- intro screen images -->
        <image name="title"    filename="title.ega"    width="320" height="200" depth="4" filetype="image/x-u4lzw" introOnly="true" fixup="intro" />
        <image name="titlex"   filename="title.ega"    width="320" height="200" depth="4" filetype="image/x-u4lzw" introOnly="true" fixup="introExtended"/>
        <image name="tree"     filename="tree.ega"     width="320" height="200" depth="4" filetype="image/x-u4lzw" introOnly="true">
            <subimage name="moongate" x="0"   y="152" width="24" height="24"/>
            <subimage name="items"    x="24"  y="152" width="24" height="24"/>
        </image>
        <image name="portal"   filename="portal.ega"   width="320" height="200" depth="4" filetype="image/x-u4lzw" introOnly="true"/>
        <image name="outside"  filename="outside.ega"  width="320" height="200" depth="4" filetype="image/x-u4lzw" introOnly="true"/>
        <image name="inside"   filename="inside.ega"   width="320" height="200" depth="4" filetype="image/x-u4lzw" introOnly="true"/>
        <image name="wagon"    filename="wagon.ega"    width="320" height="200" depth="4" filetype="image/x-u4lzw" introOnly="true"/>
        <image name="gypsy"    filename="gypsy.ega"    width="320" height="200" depth="4" filetype="image/x-u4lzw" introOnly="true"/>
        <image name="abacus"   filename="abacus.ega"   width="320" height="200" depth="4" filetype="image/x-u4lzw" introOnly="true" fixup="abacus">
            <subimage name="whitebead"      x="8"   y="187" width="8" height="12"/>
            <subimage name="blackbead"      x="24"  y="187" width="8" height="12"/>
        </image>
        <image name="honcom"   filename="honcom.ega"   width="320" height="200" depth="4" filetype="image/x-u4lzw" introOnly="true">
            <subimage name="honestycard"    x="12"  y="12" width="90" height="124"/>
            <subimage name="compassioncard" x="218" y="12" width="90" height="124"/>
        </image>
        <image name="valjus"   filename="valjus.ega"   width="320" height="200" depth="4" filetype="image/x-u4lzw" introOnly="true">
            <subimage name="valorcard"      x="12"  y="12" width="90" height="124"/>
            <subimage name="justicecard"    x="218" y="12" width="90" height="124"/>
        </image>
        <image name="sachonor" filename="sachonor.ega" width="320" height="200" depth="4" filetype="image/x-u4lzw" introOnly="true">
            <subimage name="sacrificecard"  x="12"  y="12" width="90" height="124"/>
            <subimage name="honorcard"      x="218" y="12" width="90" height="124"/>
        </image>
        <image name="spirhum"  filename="spirhum.ega"  width="320" height="200" depth="4" filetype="image/x-u4lzw" introOnly="true">
            <subimage name="spiritualitycard" x="12"  y="12" width="90" height="124"/>
            <subimage name="humilitycard"   x="218" y="12" width="90" height="124"/>
        </image>
        <image name="beasties" filename="animate.ega"  width="320" height="200" depth="4" filetype="image/x-u4lzw" introOnly="true">
            <subimage name="beast0frame00" x="0"   y="0"   width="55" height="31"/>
            <subimage name="beast0frame01" x="0"   y="32"  width="55" height="31"/>
            <subimage name="beast0frame02" x="0"   y="64"  width="55" height="31"/>
            <subimage name="beast0frame03" x="0"   y="96"  width="55" height="31"/>
            <subimage name="beast0frame04" x="0"   y="128" width="55" height="31"/>
            <subimage name="beast0frame05" x="0"   y="160" width="55" height="31"/>
            <subimage name="beast0frame06" x="56"  y="0"   width="55" height="31"/>
            <subimage name="beast0frame07" x="56"  y="32"  width="55" height="31"/>
            <subimage name="beast0frame08" x="56"  y="64"  width="55" height="31"/>
            <subimage name="beast0frame09" x="56"  y="96"  width="55" height="31"/>
            <subimage name="beast0frame10" x="56"  y="128" width="55" height="31"/>
            <subimage name="beast0frame11" x="56"  y="160" width="55" height="31"/>
            <subimage name="beast0frame12" x="112" y="0"   width="55" height="31"/>
            <subimage name="beast0frame13" x="112" y="32"  width="55" height="31"/>
            <subimage name="beast0frame14" x="112" y="64"  width="55" height="31"/>
            <subimage name="beast0frame15" x="112" y="96"  width="55" height="31"/>
            <subimage name="beast0frame16" x="112" y="128" width="55" height="31"/>
            <subimage name="beast0frame17" x="112" y="160" width="55" height="31"/>
            <subimage name="beast1frame00" x="176" y="0"   width="48" height="31"/>
            <subimage name="beast1frame01" x="176" y="32"  width="48" height="31"/>
            <subimage name="beast1frame02" x="176" y="64"  width="48" height="31"/>
            <subimage name="beast1frame03" x="176" y="96"  width="48" height="31"/>
            <subimage name="beast1frame04" x="176" y="128" width="48" height="31"/>
            <subimage name="beast1frame05" x="176" y="160" width="48" height="31"/>
            <subimage name="beast1frame06" x="224" y="0"   width="48" height="31"/>
            <subimage name="beast1frame07" x="224" y="32"  width="48" height="31"/>
            <subimage name="beast1frame08" x="224" y="64"  width="48" height="31"/>
            <subimage name="beast1frame09" x="224" y="96"  width="48" height="31"/>
            <subimage name="beast1frame10" x="224" y="128" width="48" height="31"/>
            <subimage name="beast1frame11" x="224" y="160" width="48" height="31"/>
            <subimage name="beast1frame12" x="272" y="0"   width="48" height="31"/>
            <subimage name="beast1frame13" x="272" y="32"  width="48" height="31"/>
            <subimage name="beast1frame14" x="272" y="64"  width="48" height="31"/>
            <subimage name="beast1frame15" x="272" y="96"  width="48" height="31"/>
            <subimage name="beast1frame16" x="272" y="128" width="48" height="31"/>
            <subimage name="beast1frame17" x="272" y="160" width="48" height="31"/>
        </image>

        <!-- abyss vision images: codex symbol images are overlaid on top of each other, so color 0 (black) is set to be transparent -->
        <image name="key"      filename="key7.ega"     width="320" height="200" depth="4" filetype="image/x-u4rle"/>
        <image name="honesty"  filename="honesty.ega"  width="320" height="200" depth="4" filetype="image/x-u4rle" transparentIndex="0"/>
        <image name="compassn" filename="compassn.ega" width="320" height="200" depth="4" filetype="image/x-u4rle" transparentIndex="0"/>
        <image name="valor"    filename="valor.ega"    width="320" height="200" depth="4" filetype="image/x-u4rle" transparentIndex="0"/>
        <image name="justice"  filename="justice.ega"  width="320" height="200" depth="4" filetype="image/x-u4rle" transparentIndex="0"/>
        <image name="sacrific" filename="sacrific.ega" width="320" height="200" depth="4" filetype="image/x-u4rle" transparentIndex="0"/>
        <image name="honor"    filename="honor.ega"    width="320" height="200" depth="4" filetype="image/x-u4rle" transparentIndex="0"/>
        <image name="spirit"   filename="spirit.ega"   width="320" height="200" depth="4" filetype="image/x-u4rle" transparentIndex="0"/>
        <image name="humility" filename="humility.ega" width="320" height="200" depth="4" filetype="image/x-u4rle" transparentIndex="0"/>
        <image name="truth"    filename="truth.ega"    width="320" height="200" depth="4" filetype="image/x-u4rle" transparentIndex="0"/>
        <image name="love"     filename="love.ega"     width="320" height="200" depth="4" filetype="image/x-u4rle" transparentIndex="0"/>
        <image name="courage"  filename="courage.ega"  width="320" height="200" depth="4" filetype="image/x-u4rle" transparentIndex="0"/>
        <image name="stoncrcl" filename="stoncrcl.ega" width="320" height="200" depth="4" filetype="image/x-u4rle"/>

        <!-- shrine vision images -->
        <image name="rune0"    filename="rune_5.ega"   width="320" height="200" depth="4" filetype="image/x-u4rle"/>
        <image name="rune1"    filename="rune_1.ega"   width="320" height="200" depth="4" filetype="image/x-u4rle"/>
        <image name="rune2"    filename="rune_2.ega"   width="320" height="200" depth="4" filetype="image/x-u4rle"/>
        <image name="rune3"    filename="rune_0.ega"   width="320" height="200" depth="4" filetype="image/x-u4rle"/>
        <image name="rune4"    filename="rune_1.ega"   width="320" height="200" depth="4" filetype="image/x-u4rle"/>
        <image name="rune5"    filename="rune_2.ega"   width="320" height="200" depth="4" filetype="image/x-u4rle"/>
        <image name="rune6"    filename="rune_1.ega"   width="320" height="200" depth="4" filetype="image/x-u4rle"/>
        <image name="rune7"    filename="rune_3.ega"   width="320" height="200" depth="4" filetype="image/x-u4rle"/>
        <image name="rune8"    filename="rune_4.ega"   width="320" height="200" depth="4" filetype="image/x-u4rle"/>

        <!-- gem tiles -->
        <image name="gemtiles" filename="ega/gem.png"  width="4"   height="512" depth="4" filetype="image/png" tiles="128" xu4Graphic="true"/>

        <!-- dungeon graphics -->
        <image name="dungew"    filename="ega/dungeonhall.png" width="176" height="176" depth="4" filetype="image/png" xu4Graphic="true">
