=== roydmerkel/xu4/conf/dtd/maps.dtd
<!-- $Id$ -->

<!ENTITY % bool '( true | false )'>
<!ENTITY % role '( armorvendor | companion | foodvendor | guildvendor | hawkwind | healer | 
                   horsevendor | innkeeper | lordbritish | reagentsvendor | tavernkeeper |
                   weaponsvendor )'>

<!ELEMENT maps ( map+ ) >

<!ELEMENT map ( city | compressedchunk | dungeon | moongate | portal | shrine )* >
<!ATTLIST map id                  NMTOKEN  #REQUIRED
              type                ( castle | combat | dungeon | ruins | shrine | town | village | world ) #REQUIRED
              fname               NMTOKEN  #REQUIRED
              width               NMTOKEN  #REQUIRED
              height              NMTOKEN  #REQUIRED
              levels              NMTOKEN  #REQUIRED
              chunkwidth          NMTOKEN  #IMPLIED
              chunkheight         NMTOKEN  #IMPLIED
              borderbehavior      ( exit | fixed | wrap ) #REQUIRED
              showavatar          %bool;   #IMPLIED
              nolineofsight       %bool;   #IMPLIED
              firstperson         %bool;   #IMPLIED
              music               NMTOKEN  #REQUIRED>

<!ELEMENT city ( personrole* ) >
<!ATTLIST city name               CDATA    #REQUIRED
               tlk_fname          NMTOKEN  #REQUIRED>

<!ELEMENT personrole EMPTY >
<!ATTLIST personrole role         %role;   #REQUIRED
                     id           NMTOKEN  #REQUIRED>

<!ELEMENT compressedchunk EMPTY >
<!ATTLIST compressedchunk index    NMTOKEN  #REQUIRED>

<!ELEMENT dungeon EMPTY >
<!ATTLIST dungeon name            CDATA    #REQUIRED
                  rooms           NMTOKEN  #REQUIRED>

<!ELEMENT shrine EMPTY >
<!ATTLIST shrine mantra           NMTOKEN  #REQUIRED
                 virtue           NMTOKEN  #REQUIRED>

<!ELEMENT moongate EMPTY >
<!ATTLIST moongate phase          NMTOKEN  #REQUIRED
                   x              NMTOKEN  #REQUIRED
                   y              NMTOKEN  #REQUIRED>

<!ELEMENT portal ( retroActiveDest? ) >
<!ATTLIST portal x                NMTOKEN  #REQUIRED
                 y                NMTOKEN  #REQUIRED
                 z                NMTOKEN  #REQUIRED
                 destmapid        NMTOKEN  #REQUIRED
                 startx           NMTOKEN  #REQUIRED
                 starty           NMTOKEN  #REQUIRED
                 startlevel       NMTOKEN  #REQUIRED
                 action           ( descend | enter | klimb | exit_north | exit_east | exit_south | exit_west ) #REQUIRED
                 condition        ( shrine | abyss ) #IMPLIED
                 savelocation     %bool;   #REQUIRED
                 message          CDATA    #IMPLIED
                 transport        ( foot | footorhorse ) #REQUIRED
                 exits            NMTOKEN  #IMPLIED>

<!ELEMENT retroActiveDest EMPTY >
<!ATTLIST retroActiveDest x       NMTOKEN  #REQUIRED
                          y       NMTOKEN  #REQUIRED
                          z       NMTOKEN  #REQUIRED
                          mapid   NMTOKEN  #REQUIRED>

=== roydmerkel/xu4/conf/maps.xml
<?xml version="1.0"?>
<!DOCTYPE maps SYSTEM "dtd/maps.dtd">
<!-- $Id$ -->
<maps>
    <!-- world map -->
    <map id="0" type="world" fname="world.map" width="256" height="256" levels="1" chunkwidth="32" chunkheight="32" borderbehavior="wrap" showavatar="true" music="1">        
        <portal x="86"  y="107" z="0" destmapid="1"  startx="15" starty="30" startlevel="0" action="enter" savelocation="true" transport="footorhorse"/>
        <portal x="218" y="107" z="0" destmapid="2"  startx="15" starty="30" startlevel="0" action="enter" savelocation="true" transport="footorhorse"/>
        <portal x="28"  y="50"  z="0" destmapid="3"  startx="15" starty="30" startlevel="0" action="enter" savelocation="true" transport="footorhorse"/>
        <portal x="146" y="241" z="0" destmapid="4"  startx="15" starty="30" startlevel="0" action="enter" savelocation="true" transport="footorhorse"/>

        <portal x="232" y="135" z="0" destmapid="5"  startx="1" starty="15" startlevel="0" action="enter" savelocation="true" transport="footorhorse"/>
        <portal x="82"  y="106" z="0" destmapid="6"  startx="1" starty="15" startlevel="0" action="enter" savelocation="true" transport="footorhorse"/>
        <portal x="36"  y="222" z="0" destmapid="7"  startx="1" starty="15" startlevel="0" action="enter" savelocation="true" transport="footorhorse"/>
        <portal x="58"  y="43"  z="0" destmapid="8"  startx="1" starty="15" startlevel="0" action="enter" savelocation="true" transport="footorhorse"/>
        <portal x="159" y="20"  z="0" destmapid="9"  startx="1" starty="15" startlevel="0" action="enter" savelocation="true" transport="footorhorse"/>
        <portal x="106" y="184" z="0" destmapid="10" startx="1" starty="15" startlevel="0" action="enter" savelocation="true" transport="footorhorse"/>
        <portal x="22"  y="128" z="0" destmapid="11" startx="1" starty="15" startlevel="0" action="enter" savelocation="true" transport="footorhorse"/>
        <portal x="187" y="169" z="0" destmapid="12" startx="1" starty="15" startlevel="0" action="enter" savelocation="true" transport="footorhorse"/>

        <portal x="98"  y="145" z="0" destmapid="13" startx="1" starty="15" startlevel="0" action="enter" savelocation="true" transport="footorhorse"/>
        <portal x="136" y="158" z="0" destmapid="14" startx="1" starty="15" startlevel="0" action="enter" savelocation="true" transport="footorhorse"/>
        <portal x="201" y="59"  z="0" destmapid="15" startx="1" starty="15" startlevel="0" action="enter" savelocation="true" transport="footorhorse"/>
        <portal x="136" y="90"  z="0" destmapid="16" startx="1" starty="15" startlevel="0" action="enter" savelocation="true" transport="footorhorse"/>
        
        <portal x="240" y="73"  z="0" destmapid="17" startx="1" starty="1" startlevel="0" action="enter" savelocation="true" transport="foot"/>
        <portal x="91"  y="67"  z="0" destmapid="18" startx="1" starty="1" startlevel="0" action="enter" savelocation="true" transport="foot"/>
        <portal x="72"  y="168" z="0" destmapid="19" startx="1" starty="1" startlevel="0" action="enter" savelocation="true" transport="foot"/>
        <portal x="126" y="20"  z="0" destmapid="20" startx="1" starty="1" startlevel="0" action="enter" savelocation="true" transport="foot"/>
        <portal x="156" y="27"  z="0" destmapid="21" startx="1" starty="1" startlevel="0" action="enter" savelocation="true" transport="foot"/>
        <portal x="58"  y="102" z="0" destmapid="22" startx="1" starty="1" startlevel="0" action="enter" savelocation="true" transport="foot"/>
        <portal x="239" y="240" z="0" destmapid="23" startx="1" starty="1" startlevel="0" action="enter" savelocation="true" transport="foot"/>
        <portal x="233" y="233" z="0" destmapid="24" startx="1" starty="1" startlevel="0" action="enter" condition="abyss" savelocation="true" message="Enter the Great Stygian Abyss!&#xA;&#xA;" transport="foot"/>

        <portal x="233" y="66"  z="0" destmapid="25" startx="0" starty="0" startlevel="0" action="enter" condition="shrine" savelocation="true" transport="footorhorse"/>
        <portal x="128" y="92"  z="0" destmapid="26" startx="0" starty="0" startlevel="0" action="enter" condition="shrine" savelocation="true" transport="footorhorse"/>
        <portal x="36"  y="229" z="0" destmapid="27" startx="0" starty="0" startlevel="0" action="enter" condition="shrine" savelocation="true" transport="footorhorse"/>
        <portal x="73"  y="11"  z="0" destmapid="28" startx="0" starty="0" startlevel="0" action="enter" condition="shrine" savelocation="true" transport="footorhorse"/>
        <portal x="205" y="45"  z="0" destmapid="29" startx="0" starty="0" startlevel="0" action="enter" condition="shrine" savelocation="true" transport="footorhorse"/>
        <portal x="81"  y="207" z="0" destmapid="30" startx="0" starty="0" startlevel="0" action="enter" condition="shrine" savelocation="true" transport="footorhorse"/>
        <portal x="231" y="216" z="0" destmapid="32" startx="0" starty="0" startlevel="0" action="enter" condition="shrine" savelocation="true" transport="footorhorse"/>

        <moongate phase="0" x="224" y="133"/>
        <moongate phase="1" x="96" y="102"/>
        <moongate phase="2" x="38" y="224"/>
        <moongate phase="3" x="50" y="37"/>
        <moongate phase="4" x="166" y="19"/>
        <moongate phase="5" x="104" y="194"/>
        <moongate phase="6" x="23" y="126"/>
        <moongate phase="7" x="187" y="167"/>
    </map>

    <!-- castles -->
    <map id="1" type="castle" fname="lcb_1.ult" width="32" height="32" levels="1" borderbehavior="exit" showavatar="true" music="5">
        <city name="Britannia" tlk_fname="lcb.tlk">
            <personrole role="healer" id="29"/>
            <personrole role="hawkwind" id="30"/>
        </city>
        <portal x="3" y="3" z="0" destmapid="100" startx="3" starty="3" startlevel="0" action="klimb" savelocation="false" message="Klimb to second floor!&#xA;" transport="foot"/>
        <portal x="27" y="3" z="0" destmapid="100" startx="27" starty="3" startlevel="0" action="klimb" savelocation="false" message="Klimb to second floor!&#xA;" transport="foot"/>
        <portal x="7" y="2" z="0" destmapid="23" startx="5" starty="5" startlevel="0" action="descend" savelocation="false" message="Descend into the depths!&#xA;" transport="foot">
            <retroActiveDest x="239" y="240" z="0" mapid="0"/>
        </portal>
    </map>
    <map id="100" type="castle" fname="lcb_2.ult" width="32" height="32" levels="1" borderbehavior="exit" showavatar="true" music="5">
        <city name="Britannia" tlk_fname="lcb.tlk">
            <personrole role="lordbritish" id="32"/>
        </city>
        <portal x="3" y="3" z="0" destmapid="1" startx="3" starty="3" startlevel="0" action="descend" savelocation="false" message="Descend to first floor!&#xA;" transport="foot"/>
        <portal x="27" y="3" z="0" destmapid="1" startx="27" starty="3" startlevel="0" action="descend" savelocation="false" message="Descend to first floor!&#xA;" transport="foot"/>
    </map>
    <map id="2" type="castle" fname="lycaeum.ult" width="32" height="32" levels="1" borderbehavior="exit" showavatar="true" music="9">
        <city name="Lycaeum" tlk_fname="lycaeum.tlk">
            <personrole role="healer" id="23"/>
        </city>
    </map>
    <map id="3" type="castle" fname="empath.ult" width="32" height="32" levels="1" borderbehavior="exit" showavatar="true" music="9">
        <city name="Empath Abbey" tlk_fname="empath.tlk">
            <personrole role="healer" id="30"/>
        </city>
    </map>
    <map id="4" type="castle" fname="serpent.ult" width="32" height="32" levels="1" borderbehavior="exit" showavatar="true" music="9">
        <city name="Serpents Hold" tlk_fname="serpent.tlk">
            <personrole role="healer" id="31"/>
        </city>
    </map>

    <!-- cities -->
    <map id="5" type="town" fname="moonglow.ult" width="32" height="32" levels="1" borderbehavior="exit" showavatar="true" music="2">
        <city name="Moonglow" tlk_fname="moonglow.tlk">
            <personrole role="companion" id="32"/>
            <personrole role="foodvendor" id="26"/>
            <personrole role="reagentsvendor" id="24"/>
            <personrole role="healer" id="25"/>
            <personrole role="innkeeper" id="30"/>
        </city>
    </map>
    <map id="6" type="town" fname="britain.ult" width="32" height="32" levels="1" borderbehavior="exit" showavatar="true" music="2">
        <city name="Britain" tlk_fname="britain.tlk">
            <personrole role="companion" id="32"/>
            <personrole role="weaponsvendor" id="29"/>
            <personrole role="armorvendor" id="28"/>
            <personrole role="foodvendor" id="27"/>
            <personrole role="tavernkeeper" id="26"/>
            <personrole role="healer" id="31"/>
            <personrole role="innkeeper" id="25"/>
        </city>
    </map>
    <map id="7" type="town" fname="jhelom.ult" width="32" height="32" levels="1" borderbehavior="exit" showavatar="true" music="2">
        <city name="Jhelom" tlk_fname="jhelom.tlk">
            <personrole role="companion" id="32"/>
            <personrole role="weaponsvendor" id="29"/>
            <personrole role="armorvendor" id="28"/>
            <personrole role="tavernkeeper" id="30"/>
            <personrole role="healer" id="25"/>
            <personrole role="healer" id="26"/>
            <personrole role="healer" id="27"/>
            <personrole role="innkeeper" id="31"/>
         </city>
    </map>
    <map id="8" type="town" fname="yew.ult" width="32" height="32" levels="1" borderbehavior="exit" showavatar="true" music="2">
        <city name="Yew" tlk_fname="yew.tlk">
            <personrole role="companion" id="32"/>
            <personrole role="foodvendor" id="27"/>
            <personrole role="healer" id="26"/>
        </city>
    </map>
