=== roydmerkel/xu4/conf/dtd/tiles.dtd
<!-- $Id$ -->

<!ENTITY % bool '( true | false )'>
<!ENTITY % comp '( none | rle | lzw )'>
<!ENTITY % anim '( scroll | frames | rowswap | none )'>

<!ELEMENT tiles ( tile+ ) >

<!ELEMENT tile EMPTY >
<!ATTLIST tile  name               CDATA    #REQUIRED
                rule               CDATA    #IMPLIED
                frames             NMTOKEN  #IMPLIED
                directions         CDATA    #IMPLIED
                animated           %bool;   #IMPLIED
                rowtoswap          NMTOKEN  #IMPLIED
                opaque             %bool;   #IMPLIED>

<!-- animation          %anim;   #IMPLIED -->

=== roydmerkel/xu4/conf/dungeonTiles.xml
<?xml version="1.0"?>
<!DOCTYPE tiles SYSTEM "dtd/tiles.dtd">
<!-- $Id$ -->
<tiles>
    <tile name="dungeon_floor" displayTile="62" rule="floors" frames="16"/>
    <tile name="up_ladder" displayTile="27" frames="16"/>
    <tile name="down_ladder" displayTile="28" frames="16"/>
    <tile name="up_down_ladder" displayTile="27" frames="16"/>
    <tile name="chest" displayTile="60" rule="chest" frames="16"/>
    <tile name="ceiling_hole" displayTile="62" frames="16"/>
    <tile name="floor_hole" displayTile="62" frames="16"/>
    <tile name="magic_orb" displayTile="78" frames="16"/>
    <tile name="trap" displayTile="62" frames="16"/>
    <tile name="fountain" displayTile="2" frames="16" animated="true"/>    
    <tile name="poison_field" displayTile="68" rule="poison_field"/>
    <tile name="energy_field" displayTile="69" rule="energy_field"/>
    <tile name="fire_field" displayTile="70" rule="fire_field"/>
    <tile name="sleep_field" displayTile="71" rule="sleep_field"/>
    <tile name="unused_fields" displayTile="68" frames="12"/>
    <tile name="altar" displayTile="74" rule="dng_altar" frames="16"/>
    <tile name="door" displayTile="59" rule="dng_door" frames="16"/>
    <tile name="room" displayTile="72" rule="dng_room" frames="16"/>
    <tile name="secret_door" displayTile="127" rule="secret_door" frames="16"/>
    <tile name="brick_wall" displayTile="127" rule="walls" frames="16"/>    
</tiles>

=== roydmerkel/xu4/conf/tiles.xml
<?xml version="1.0"?>
<!DOCTYPE tiles SYSTEM "dtd/tiles.dtd">
<!-- $Id$ -->

<tiles>
    <tile name="sea" rule="water" animation="scroll"/>
    <tile name="water" rule="water" animation="scroll"/>
    <tile name="shallows" rule="shallows" animation="scroll"/>
    <tile name="swamp" rule="swamp"/>
    <tile name="grass" rule="grass"/>
    <tile name="brush" rule="brush"/>
    <tile name="forest" rule="brush" opaque="true"/>
    <tile name="hills" rule="hills"/>
    <tile name="mountains" rule="mountains" opaque="true"/>
    <tile name="dungeon"/>
    <tile name="city" animation="cityflag"/>
    <tile name="castle" animation="castleflag"/>
    <tile name="town"/>
    <tile name="lcb_west" rule="lcb"/>
    <tile name="lcb_entrance" rule="lcb_entrance" animation="lcbflag"/>
    <tile name="lcb_east" rule="lcb"/>
    <tile name="ship" rule="ship" frames="4" directions="nesw" animation="shipflag"/>
    <tile name="horse" rule="horse" frames="2" directions="ew"/>
    <tile name="dungeon_floor" rule="floors"/>
    <tile name="bridge"/>
    <tile name="balloon" rule="balloon"/>
    <tile name="bridge_pieces" frames="2"/>
    <tile name="up_ladder"/>
    <tile name="down_ladder"/>
    <tile name="ruins"/>
    <tile name="shrine"/>
    <tile name="avatar" rule="person"/>
    <tile name="mage" rule="person" frames="2" animation="frames"/>
    <tile name="bard" rule="person" frames="2" animation="frames"/>
    <tile name="fighter" rule="person" frames="2" animation="frames"/>
    <tile name="druid" rule="person" frames="2" animation="frames"/>
    <tile name="tinker" rule="person" frames="2" animation="frames"/>
    <tile name="paladin" rule="person" frames="2" animation="frames"/>
    <tile name="ranger" rule="person" frames="2" animation="frames"/>
    <tile name="shepherd" rule="person" frames="2" animation="frames"/>
    <tile name="column" rule="solid"/>
    <tile name="solids" rule="solid_attackover" frames="4"/>
    <tile name="shipmast" rule="solid"/>
    <tile name="shipwheel" rule="solid"/>
    <tile name="rocks" rule="solid"/>
    <tile name="corpse" rule="solid"/>
    <tile name="stone_wall" rule="walls"/>
    <tile name="locked_door" rule="locked_door"/>
    <tile name="door" rule="door"/>
    <tile name="chest" rule="chest"/>
    <tile name="ankh" rule="solid"/>
    <tile name="brick_floor" rule="floors"/>
    <tile name="wood_floor" rule="floors"/>
    <tile name="moongate_opening" rule="solid" frames="3"/>
    <tile name="moongate"/>
    <tile name="poison_field" rule="poison_field" animation="scroll"/>
    <tile name="energy_field" rule="energy_field" animation="scroll"/>
    <tile name="fire_field" rule="fire_field" animation="scroll"/>
    <tile name="sleep_field" rule="sleep_field" animation="scroll"/>
    <tile name="solid" rule="solid_attackover"/>
    <tile name="secret_door" opaque="true"/>
    <tile name="altar"/>
    <tile name="campfire" rule="solid" animation="campfire"/>
    <tile name="lava" rule="lava" animation="scroll"/>
    <tile name="miss_flash"/>
    <tile name="magic_flash"/>
    <tile name="hit_flash"/>
    <tile name="guard" rule="person" frames="2" animation="frames"/>
    <tile name="villager" rule="person" frames="2" animation="frames"/>
    <tile name="bard_singing" rule="person" frames="2" animation="frames"/>    
    <tile name="jester" rule="person" frames="2" animation="frames"/>
    <tile name="beggar" rule="person" frames="2" animation="frames"/>
    <tile name="child" rule="person" frames="2" animation="frames"/>
    <tile name="bull" rule="person" frames="2" animation="frames"/>
    <tile name="lord_british" rule="person" frames="2" animation="frames"/>
    <tile name="signs" rule="signs" frames="27"/> <!-- the alphabet -->    
    <tile name="spacers" rule="spacers" frames="3"/> <!-- sign spacers -->
    <tile name="black" rule="spacers"/> <!-- black square -->
    <tile name="brick_wall" rule="walls" opaque="true"/>

    <!-- Water monsters -->
    <tile name="pirate_ship" rule="monster" frames="4" directions="nesw"/>
    <tile name="nixie" rule="monster" frames="2" animation="frames"/>
    <tile name="giant_squid" rule="monster" frames="2" animation="frames"/>
    <tile name="sea_serpent" rule="monster" frames="2" animation="frames"/>
    <tile name="sea_horse" rule="monster" frames="2" animation="frames"/>
    <tile name="whirlpool" frames="2" animation="frames"/>
    <tile name="storm" frames="2" animation="frames"/>
    
    <!-- Land monsters -->    
    <tile name="rat" rule="monster" frames="4" animation="frames"/>
    <tile name="bat" rule="monster" frames="4" animation="frames"/>
    <tile name="spider" rule="monster" frames="4" animation="frames"/>
    <tile name="ghost" rule="monster" frames="4" animation="frames"/>
    <tile name="slime" rule="monster" frames="4" animation="frames"/>
    <tile name="troll" rule="monster" frames="4" animation="frames"/>
    <tile name="gremlin" rule="monster" frames="4" animation="frames"/>
    <tile name="mimic" rule="monster" frames="4" animation="frames"/>
    <tile name="reaper" rule="monster" frames="4" animation="frames"/>
    <tile name="insect_swarm" rule="monster" frames="4" animation="frames"/>
    <tile name="gazer" rule="monster" frames="4" animation="frames"/>
    <tile name="phantom" rule="monster" frames="4" animation="frames"/>
    <tile name="orc" rule="monster" frames="4" animation="frames"/>
    <tile name="skeleton" rule="monster" frames="4" animation="frames"/>
    <tile name="rogue" rule="monster" frames="4" animation="frames"/>
    <tile name="python" rule="monster" frames="4" animation="frames"/>
    <tile name="ettin" rule="monster" frames="4" animation="frames"/>
    <tile name="headless" rule="monster" frames="4" animation="frames"/>
    <tile name="cyclops" rule="monster" frames="4" animation="frames"/>
    <tile name="wisp" rule="monster" frames="4" animation="frames"/>
    <tile name="evil_mage" rule="monster" frames="4" animation="frames"/>
    <tile name="liche" rule="monster" frames="4" animation="frames"/>
    <tile name="lava_lizard" rule="monster" frames="4" animation="frames"/>
    <tile name="zorn" rule="monster" frames="4" animation="frames"/>
    <tile name="daemon" rule="monster" frames="4" animation="frames"/>
    <tile name="hydra" rule="monster" frames="4" animation="frames"/>
    <tile name="dragon" rule="monster" frames="4" animation="frames"/>
    <tile name="balron" rule="monster" frames="4" animation="frames"/>    
</tiles>
