=== roydmerkel/xu4/conf/dtd/tilemap.dtd
<!-- $Id$ -->

<!ELEMENT tilemap ( map+ ) >
<!ATTLIST tilemap name             CDATA    #REQUIRED>

<!ELEMENT map EMPTY >
<!ATTLIST map tile                 CDATA    #REQUIRED
              index                NMTOKEN  #IMPLIED
              frames               NMTOKEN  #IMPLIED>

=== roydmerkel/xu4/conf/tilemap-dungeon.xml
<?xml version="1.0"?>
<!-- <!DOCTYPE tilemap SYSTEM "dtd/tilemap.dtd">-->
<!-- $Id$ -->

<tilemap name="dungeon">   
    <map frames="16" tile="brick_floor"/>
    <map frames="16" tile="up_ladder"/>
    <map frames="16" tile="down_ladder"/>
    <map frames="16" tile="up_down_ladder"/>
    <map frames="16" tile="chest"/>
    <map frames="16" tile="ceiling_hole"/>
    <map frames="16" tile="floor_hole"/>
    <map frames="16" tile="magic_orb"/>
    
    <map frames="16" tile="ceiling_hole"/>
    <!--
    <map tile="wind_trap"/>
    <map tile="falling_rock_trap"/>
    <map frames="12" tile="brick_floor"/>
    <map tile="pit_trap"/>
    <map tile="dungeon_floor"/>
    -->

    <map frames="16" tile="fountain"/>
    <!--
    <map tile="fountain_normal"/>
    <map tile="fountain_healing"/>
    <map tile="fountain_acid"/>
    <map tile="fountain_cure"/>
    <map tile="fountain_poison"/>
    <map frames="11" tile="brick_floor"/>
    -->

    <map tile="poison_field"/>
    <map tile="energy_field"/>
    <map tile="fire_field"/>
    <map tile="sleep_field"/>
    <map frames="12" tile="brick_floor"/> <!-- unused fields -->
    <map frames="16" tile="dungeon_altar"/>
    <map frames="16" tile="dungeon_door"/>
    <map frames="16" tile="dungeon_room"/>
    <map frames="16" tile="secret_door"/>
    <map frames="16" tile="brick_wall"/>
</tilemap>

=== roydmerkel/xu4/u4/conf/tileset/tilemap/base.xml
<?xml version="1.0"?>
<!-- <!DOCTYPE tilemap SYSTEM "dtd/tilemap.dtd">-->
<!-- $Id$ -->

<tilemap name="base">
    <map tile="sea"/>
    <map tile="water"/>
    <map tile="shallows"/>
    <map tile="swamp"/>
    <map tile="grass"/>
    <map tile="brush"/>
    <map tile="forest"/>
    <map tile="hills"/>
    <map tile="mountains"/>
    <map tile="dungeon"/>
    <map tile="city"/>
    <map tile="castle"/>
    <map tile="town"/>
    <map tile="lcb_west"/>
    <map tile="lcb_entrance"/>
    <map tile="lcb_east"/>
    <map frames="4" tile="ship"/>
    <map frames="2" tile="horse"/>
    <map tile="dungeon_floor"/>    
    <map tile="bridge"/>
    <map tile="balloon"/>
    <map frames="2" tile="bridge_pieces"/>
    <map tile="up_ladder"/>
    <map tile="down_ladder"/>
    <map tile="ruins"/>    
    <map tile="shrine"/>
    <map tile="avatar"/>
    <map frames="2" tile="mage"/>
    <map frames="2" tile="bard"/>
    <map frames="2" tile="fighter"/>
    <map frames="2" tile="druid"/>
    <map frames="2" tile="tinker"/>
    <map frames="2" tile="paladin"/>
    <map frames="2" tile="ranger"/>
    <map frames="2" tile="shepherd"/>
    <map tile="column"/>
    <map frames="4" tile="solids"/>
    <map tile="shipmast"/>
    <map tile="shipwheel"/>
    <map tile="rocks"/>
    <map tile="corpse"/>
    <map tile="stone_wall"/>
    <map tile="locked_door"/>
    <map tile="door"/>
    <map tile="chest"/>
    <map tile="ankh"/>
    <map tile="brick_floor"/>
    <map tile="wood_floor"/>
    <map frames="3" tile="moongate_opening"/>
    <map tile="moongate"/>
    <map tile="poison_field"/>
    <map tile="energy_field"/>
    <map tile="fire_field"/>
    <map tile="sleep_field"/>
    <map tile="solid"/>
    <map tile="secret_door"/>
    <map tile="altar"/>
    <map tile="campfire"/>
    <map tile="lava"/>
    <map tile="miss_flash"/>
    <map tile="magic_flash"/>
    <map tile="hit_flash"/>
    <map frames="2" tile="guard"/>
    <map frames="2" tile="villager"/>
    <map frames="2" tile="bard_singing"/>
    <map frames="2" tile="jester"/>
    <map frames="2" tile="beggar"/>
    <map frames="2" tile="child"/>
    <map frames="2" tile="bull"/>
    <map frames="2" tile="lord_british"/>
    <map frames="27" tile="signs"/>
    <map frames="3" tile="spacers"/>
    <map tile="black"/>
    <map tile="brick_wall"/>

    <!-- Water monsters -->
    <map frames="4" tile="pirate_ship"/>
    <map frames="2" tile="nixie"/>
    <map frames="2" tile="giant_squid"/>
    <map frames="2" tile="sea_serpent"/>
    <map frames="2" tile="sea_horse"/>
    <map frames="2" tile="whirlpool"/>
    <map frames="2" tile="storm"/>
    
    <!-- Land monsters -->    
    <map frames="4" tile="rat"/>
    <map frames="4" tile="bat"/>
    <map frames="4" tile="spider"/>
    <map frames="4" tile="ghost"/>
    <map frames="4" tile="slime"/>
    <map frames="4" tile="troll"/>
    <map frames="4" tile="gremlin"/>
    <map frames="4" tile="mimic"/>
    <map frames="4" tile="reaper"/>
    <map frames="4" tile="insect_swarm"/>
    <map frames="4" tile="gazer"/>
    <map frames="4" tile="phantom"/>
    <map frames="4" tile="orc"/>
    <map frames="4" tile="skeleton"/>
    <map frames="4" tile="rogue"/>
    <map frames="4" tile="python"/>
    <map frames="4" tile="ettin"/>
    <map frames="4" tile="headless"/>
    <map frames="4" tile="cyclops"/>
    <map frames="4" tile="wisp"/>
    <map frames="4" tile="evil_mage"/>
    <map frames="4" tile="liche"/>
    <map frames="4" tile="lava_lizard"/>
    <map frames="4" tile="zorn"/>
    <map frames="4" tile="daemon"/>
    <map frames="4" tile="hydra"/>
    <map frames="4" tile="dragon"/>
    <map frames="4" tile="balron"/>
</tilemap>
