=== roydmerkel/xu4/u4/conf/dtd/armors.dtd
<!-- $Id$ -->

<!ELEMENT armors ( armor+ ) >

<!ELEMENT armor ( constraint* ) >
<!ATTLIST armor name       CDATA   #REQUIRED
                defense    NMTOKEN #REQUIRED>

=== roydmerkel/xu4/conf/armors.xml
<?xml version="1.0"?>
<!DOCTYPE armors SYSTEM "dtd/armors.dtd">
<!-- $Id$ -->
<armors>
    <armor name="Skin" defense="96"/>	
    <armor name="Cloth" defense="128"/>	
    <armor name="Leather" defense="144" cantwear="mage, druid, shepherd"/>	
    <armor name="Chain Mail" defense="160" canwear="tinker, fighter, paladin"/>	
    <armor name="Plate Mail" defense="176" canwear="tinker, fighter, paladin"/>
    <armor name="Magic Chain" defense="192" canwear="tinker, fighter, paladin"/>	
    <armor name="Magic Plate" defense="208" canwear="tinker, fighter, paladin"/>	
    <armor name="Mystic Robe" defense="248"/>	
</armors>
