=== roydmerkel/xu4/u4/conf/dtd/egaPalette.dtd
<!-- $Id$ -->

<!ELEMENT egaPalette ( color+ ) >

<!ELEMENT color EMPTY >
<!ATTLIST color r                 NMTOKEN  #REQUIRED
                g                 NMTOKEN  #REQUIRED
                b                 NMTOKEN  #REQUIRED>

=== roydmerkel/xu4/u4/conf/egaPalette.xml
<?xml version="1.0"?>
<!DOCTYPE egaPalette SYSTEM "dtd/egaPalette.dtd" [
  <!ENTITY % color SYSTEM "dtd/color.dtd">
  %color;
]>

<!-- $Id$ -->
<egaPalette>    
    <color red="0" green="0" blue="0"/>          <!-- black --> 
    <color red="0" green="0" blue="162"/>        <!-- blue -->
    <color red="0" green="162" blue="0"/>        <!-- green -->
    <color red="0" green="162" blue="162"/>      <!-- blue-green -->
    <color red="162" green="0" blue="0"/>        <!-- red -->
    <color red="162" green="0" blue="162"/>      <!-- purple -->
    <color red="170" green="85" blue="0"/>       <!-- brown -->
    <color red="168" green="168" blue="168"/>    <!-- lt. gray -->
    <color red="82" green="82" blue="82"/>       <!-- gray -->
    <color red="80" green="80" blue="255"/>      <!-- bright blue -->
    <color red="80" green="255" blue="80"/>      <!-- bright green -->
    <color red="80" green="255" blue="255"/>     <!-- bright blue-green -->
    <color red="255" green="80" blue="80"/>      <!-- bright red -->
    <color red="255" green="80" blue="255"/>     <!-- magenta -->
    <color red="255" green="255" blue="80"/>     <!-- yellow --> 
    <color red="255" green="255" blue="255"/>    <!-- white -->
</egaPalette>
